name: 'Checkmarx AST CLI Action'
description: 'Simplify Checkmarx Scanning of source code along with Result consumption leveraging Checkmarx AST solution.'
author: 'Checkmarx Technical Services'
inputs:
  base_uri:
    required: true
    description: 'Provide the AST portal URL'
    default: 'http://demo.ast-cloud.com'
  cx_apikey:
    required: false
    description: 'Token for AST portal authentication'
    default: ''
  scan_types:
    required: true
    description: 'Scan types to perform on AST'
    default: ''
  project_name:
    required: false
    default: ${{ github.repository }} # default repo name
    description: 'Select a Checkmarx Project Name'
  source_directory:
    required: false
    default: '.'
    description: 'Source for the project directory'
  filter:
    required: false
    default: '*'
    description: 'Project scan filters for AST'
  additional_params:
    required: false
    default: ''
    description: 'Additional parameters for AST scan'
outputs: 
  cxcli:
    description: output from cli
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base_uri }}
    - ${{ inputs.cx_apikey }}
    - ${{ inputs.github_token }}
    - ${{ inputs.scan_types }}
    - ${{ inputs.project_name }}
    - ${{ inputs.source_directory }}
    - ${{ inputs.additional_params }}
    - ${{ inputs.filter }}

  env:
    CX_BASE_URI: "${{ inputs.base_uri }}"
    CX_TOKEN: ${{ inputs.cx_apikey }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    SCAN_TYPES: ${{ inputs.scan_types }}
    PROJECT_NAME: ${{ inputs.project_name }}
    SOURCE_DIRECTORY: ${{ inputs.source_directory }}
    ADDITIONAL_PARAMS: ${{ inputs.additional_params }}
    FILTER: ${{ inputs.filter }}

branding:
  icon: 'check'
  color: 'green'
